# Generated by Django 3.0.5 on 2020-12-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.TextField(default='No image available'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
